spring:
  application:
    name: ks-supersync-unasapi
eureka:
  client:
    serviceUrl:
      defaultZone: https://supersync-eureka.herokuapp.com/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
ribbon:
    ReadTimeout: 14000